name: ci with Pull Request

on:
  push:
  pull_request:
  branches:
  - main

jobs:
  dhruva:

    runs-on: ubuntu-latest
    steps:
    - name: check out pull Request
    - uses: action/checkout@v4
    - name: run the dependancy
    - run: npm i
    - name: run the ci
    - run: npm start
